# Generated by Django 5.1.7 on 2025-03-29 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='research_id',
            new_name='research',
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='research_id',
            new_name='research',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='user_id',
            new_name='user',
        ),
    ]
